# Generated by Django 3.1.2 on 2021-03-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='nome_changelog',
        ),
    ]
