# Generated by Django 3.1.2 on 2020-11-28 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestaoteste', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeveridadeBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidade_bug', models.CharField(blank=True, max_length=15, verbose_name='Status do Bug')),
            ],
        ),
        migrations.CreateModel(
            name='StatusBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_bug', models.CharField(blank=True, max_length=15, verbose_name='Status do Bug')),
            ],
        ),
        migrations.CreateModel(
            name='GestaoBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bug', models.CharField(max_length=12, verbose_name='Código do Bug')),
                ('nome_bug', models.CharField(max_length=12, verbose_name='Nome do Bug')),
                ('desenvolvedor_responsavel', models.CharField(max_length=30, verbose_name='Desenvolvedor Responsável')),
                ('relator_bug', models.CharField(max_length=30, verbose_name='Relator do Bug Responsável')),
                ('descricao_bug', models.TextField(blank=True, verbose_name='Descrição do Bug')),
                ('upload_bug', models.FileField(blank=True, upload_to='documentos', verbose_name='Evidências')),
                ('ct_relacionado', models.ManyToManyField(blank=True, to='gestaoteste.GestaoTeste', verbose_name='Caso(s) de Teste(s) Relacionado(s)')),
                ('severidad_bug', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gestaobug.severidadebug')),
            ],
        ),
    ]
