# Generated by Django 3.1.2 on 2020-11-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaobug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestaobug',
            name='status_bug',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='gestaobug.statusbug'),
            preserve_default=False,
        ),
    ]
