# Generated by Django 3.1.2 on 2020-12-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaobug', '0003_auto_20201128_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestaobug',
            old_name='severidad_bug',
            new_name='severidade_bug',
        ),
        migrations.AlterField(
            model_name='gestaobug',
            name='nome_bug',
            field=models.CharField(max_length=30, verbose_name='Nome do Bug'),
        ),
        migrations.AlterField(
            model_name='severidadebug',
            name='severidade_bug',
            field=models.CharField(blank=True, max_length=30, verbose_name='Severidade do Bug'),
        ),
        migrations.AlterField(
            model_name='statusbug',
            name='status_bug',
            field=models.CharField(blank=True, max_length=30, verbose_name='Status do Bug'),
        ),
    ]
