# Generated by Django 3.1.2 on 2020-12-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaobug', '0004_auto_20201202_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestaobug',
            name='relator_bug',
            field=models.CharField(max_length=30, verbose_name='Relator do Bug'),
        ),
    ]
