# Generated by Django 3.1.2 on 2020-12-09 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisitos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestaoTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_caso_teste', models.CharField(max_length=30, verbose_name='Nome do Caso de Teste')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código do Caso de Teste')),
                ('caso_de_teste_doc', models.FileField(blank=True, upload_to='documentos')),
                ('objetivo_teste', models.CharField(blank=True, max_length=50, verbose_name='Objetivo do teste')),
                ('status', models.CharField(blank=True, max_length=15, verbose_name='Status do Caso de Teste')),
                ('caso_de_teste', models.TextField(blank=True, verbose_name='Caso de Teste')),
                ('resultados_esperados', models.TextField(blank=True, verbose_name='Resultados esperados')),
                ('prioridade', models.CharField(blank=True, max_length=15, verbose_name='Prioridade')),
                ('automatizado', models.BooleanField(default=False)),
                ('requisito_associado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='requisitos.requisito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
