# Generated by Django 3.1.2 on 2021-03-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0004_auto_20210306_2140'),
        ('gestaoteste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestaoteste',
            name='caso_de_teste',
            field=models.TextField(blank=True, null=True, verbose_name='Caso de Teste'),
        ),
        migrations.AlterField(
            model_name='gestaoteste',
            name='caso_de_teste_doc',
            field=models.FileField(blank=True, null=True, upload_to='documentos'),
        ),
        migrations.AlterField(
            model_name='gestaoteste',
            name='objetivo_teste',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Objetivo do teste'),
        ),
        migrations.AlterField(
            model_name='gestaoteste',
            name='prioridade',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='gestaoteste',
            name='requisito_associado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='requisitos.requisito'),
        ),
        migrations.AlterField(
            model_name='gestaoteste',
            name='resultados_esperados',
            field=models.TextField(blank=True, null=True, verbose_name='Resultados esperados'),
        ),
        migrations.AlterField(
            model_name='gestaoteste',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Status do Caso de Teste'),
        ),
    ]
