# Generated by Django 3.1.2 on 2020-11-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoteste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestaoteste',
            name='automatizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gestaoteste',
            name='codigo',
            field=models.CharField(default=1, max_length=10, verbose_name='Código do Caso de Teste'),
            preserve_default=False,
        ),
    ]
