# Generated by Django 3.1.2 on 2020-11-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoteste', '0002_auto_20201109_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestaoteste',
            name='objetivo_teste',
            field=models.CharField(blank=True, max_length=50, verbose_name='Objetivo do teste'),
        ),
        migrations.AddField(
            model_name='gestaoteste',
            name='resultados_esperados',
            field=models.TextField(blank=True, verbose_name='Resultados esperados'),
        ),
    ]
