# Generated by Django 3.1.2 on 2020-10-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=70)),
                ('nomeEmpresa', models.CharField(max_length=80)),
                ('endereco', models.TextField(max_length=100)),
                ('cpf', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=40)),
                ('celular', models.CharField(max_length=40)),
                ('cargo', models.CharField(max_length=20)),
            ],
        ),
    ]
