# Generated by Django 3.1.2 on 2020-10-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_cadastro_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='user',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cargo',
            field=models.CharField(max_length=20, verbose_name='Cargo: '),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='celular',
            field=models.CharField(max_length=40, verbose_name='Celular (com DDD): '),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(max_length=13, verbose_name='CPF: '),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='E-mail: '),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='endereco',
            field=models.TextField(max_length=100, verbose_name='Endereço Completo: '),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nomeCompleto',
            field=models.CharField(max_length=70, verbose_name='Nome Completo: '),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nomeEmpresa',
            field=models.CharField(max_length=80, verbose_name='Nome da Empresa: '),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(max_length=40, verbose_name='Telefone (com DDD): '),
        ),
    ]
