# Generated by Django 3.1.2 on 2021-03-09 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusprojeto', models.CharField(max_length=20, verbose_name='Status do Projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProjeto', models.CharField(max_length=20, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Projeto')),
                ('dtInicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('nomeSprint', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome da Sprint')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.statusprojeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
