# Generated by Django 3.1.2 on 2020-10-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProjeto', models.CharField(max_length=20)),
                ('descricao', models.TextField(max_length=100)),
                ('dtInicio', models.DateField()),
                ('deadline', models.DateField()),
                ('nomeSprint', models.CharField(max_length=30)),
                ('status', models.TextField(max_length=20)),
            ],
        ),
    ]
