# Generated by Django 3.1.2 on 2020-10-18 23:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
