# Generated by Django 3.1.2 on 2020-12-28 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusprojeto', models.CharField(max_length=20, verbose_name='Status do Projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.statusprojeto'),
        ),
    ]
