# Generated by Django 3.1.2 on 2021-01-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_auto_20201228_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='dtInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nomeSprint',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome da Sprint'),
        ),
    ]
