# Generated by Django 3.1.2 on 2020-11-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_auto_20201025_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='deadline',
            field=models.DateField(blank=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='dtInicio',
            field=models.DateField(blank=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nomeSprint',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nome da Sprint'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Status'),
        ),
    ]
