# Generated by Django 3.1.2 on 2020-12-09 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projeto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeRequisito', models.CharField(max_length=30, verbose_name='Nome do Requisito')),
                ('responsavel', models.CharField(blank=True, max_length=30, verbose_name='Responsável pelo Desenvolvimento')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código do Requisito')),
                ('ponto_focal', models.CharField(blank=True, max_length=20, verbose_name='Ponto Focal')),
                ('prioridade', models.CharField(blank=True, max_length=10, verbose_name='Prioridade do Requisito')),
                ('risco', models.CharField(blank=True, max_length=10, verbose_name='Risco do Requisito')),
                ('motivo', models.CharField(blank=True, max_length=100, verbose_name='Motivo do Requisito')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Status do Requisito')),
                ('storypoints', models.CharField(blank=True, max_length=3, verbose_name='Story Points')),
                ('requisitosImpactados', models.TextField(blank=True, verbose_name='Requisitos Impactados')),
                ('documento', models.FileField(blank=True, upload_to='documentos')),
                ('estoriaUsuario', tinymce.models.HTMLField()),
                ('regrasNegocio', tinymce.models.HTMLField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
