# Generated by Django 3.1.2 on 2020-11-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Motivo do Requisito'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='prioridade',
            field=models.CharField(blank=True, max_length=10, verbose_name='Prioridade do Requisito'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='requisitosImpactados',
            field=models.TextField(blank=True, verbose_name='Requisitos Impactados'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='risco',
            field=models.CharField(blank=True, max_length=10, verbose_name='Risco do Requisito'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Status do Requisito'),
        ),
    ]
