# Generated by Django 3.1.2 on 2020-10-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='status',
            field=models.CharField(default=1, max_length=20, verbose_name='Status do Requisito'),
            preserve_default=False,
        ),
    ]
