# Generated by Django 3.1.2 on 2020-12-29 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisitos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='estoriaUsuario',
            field=models.TextField(blank=True, verbose_name='Estória do Usuário'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='regrasNegocio',
            field=models.TextField(blank=True, verbose_name='Regras de Negócios'),
        ),
        migrations.CreateModel(
            name='StatusRequisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_requisito', models.CharField(blank=True, max_length=20, verbose_name='Status do Requisito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiscoRequisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risco_requisito', models.CharField(blank=True, max_length=20, verbose_name='Risco do Requisito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrioridadeRequisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade_requisito', models.CharField(blank=True, max_length=20, verbose_name='Prioridade do Requisito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='requisito',
            name='prioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requisitos.prioridaderequisito'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='risco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requisitos.riscorequisito'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requisitos.statusrequisito'),
        ),
    ]
