# Generated by Django 3.1.2 on 2021-01-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0002_auto_20201229_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='urlJira',
            field=models.URLField(blank=True, verbose_name='URL no JIRA'),
        ),
        migrations.AddField(
            model_name='requisito',
            name='urlRepositorio',
            field=models.URLField(blank=True, verbose_name='URL no Repositório'),
        ),
    ]
