# Generated by Django 3.1.2 on 2020-11-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0002_auto_20201108_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='ponto_focal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ponto Focal'),
        ),
    ]
