# Generated by Django 3.1.2 on 2021-03-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0003_auto_20210116_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='estoriaUsuario',
            field=models.TextField(blank=True, null=True, verbose_name='Estória do Usuário'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo do Requisito'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='ponto_focal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ponto Focal'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='regrasNegocio',
            field=models.TextField(blank=True, null=True, verbose_name='Regras de Negócios'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='requisitosImpactados',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos Impactados'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='responsavel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Responsável pelo Desenvolvimento'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='storypoints',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Story Points'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='urlJira',
            field=models.URLField(blank=True, null=True, verbose_name='URL no JIRA'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='urlRepositorio',
            field=models.URLField(blank=True, null=True, verbose_name='URL no Repositório'),
        ),
    ]
